services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dien-may-long-bien-db
      TZ: UTC
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_config:/etc/postgresql/conf.d
    restart: unless-stopped

volumes:
  postgres_data:
  postgres_config:
